name       : python-pandas
version    : 1.3.5
release    : 16
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.3.5/pandas-1.3.5.tar.gz : 1e4285f5de1012de20ca46b188ccf33521bff61ba5c5ebd78b4fb28e5416a9f1
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil # check
    - python-pytest # check
    - python-pytz # check
rundeps    :
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    requires pytest 5
#    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
