name       : python-pandas
version    : 0.23.0
release    : 6
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v0.23.0/pandas-0.23.0.tar.gz : 84ab1d50590cb2d9554211f164dc1b1a216bc94da2ba922aed2690c83f248fd9
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-setuptools
rundeps    :
    - numpy
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
