name       : python-pandas
version    : 1.3.4
release    : 15
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.3.4/pandas-1.3.4.tar.gz : a2aa18d3f0b7d538e21932f637fbfe8518d085238b429e4790a35e1e44a96ffc
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil # check
    - python-pytest # check
    - python-pytz # check
rundeps    :
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    requires pytest 5
#    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
