name       : python-pandas
version    : 1.5.1
release    : 21
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.5.1/pandas-1.5.1.tar.gz : 249cec5f2a5b22096440bd85c33106b6102e0672204abd2d5c014106459804ee
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil # check
    - python-pytest   # check
    - python-pytz     # check
rundeps    :
    - python-bottleneck # optional
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
