name       : python-pandas
version    : 1.2.2
release    : 10
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.2.2/pandas-1.2.2.tar.gz : 14ed84b463e9b84c8ff9308a79b04bf591ae3122a376ee0f62c68a1bd917a773
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
rundeps    :
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
