name       : python-pandas
version    : 0.20.3
release    : 1
source     :
    - https://github.com/pandas-dev/pandas/archive/v0.20.3.tar.gz : f09c8f999611c2a4c073b5fa3ec212b859b5569e14a59f084f47f4203c2d0600
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-setuptools
rundeps    :
    - numpy
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
