name       : python-pandas
version    : 1.4.4
release    : 20
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.4.4/pandas-1.4.4.tar.gz : ab6c0d738617b675183e5f28db32b5148b694ad9bba0a40c3ea26d96b431db67
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil # check
    - python-pytest   # check
    - python-pytz     # check
rundeps    :
    - python-bottleneck # optional
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
