name       : python-pandas
version    : 0.22.0
release    : 3
source     :
    - https://github.com/pandas-dev/pandas/archive/v0.22.0.tar.gz : 15b358650d6f7f432e31fe85cc508b3eba09069bc00b64b4ec3d698e0887c5f3
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-setuptools
rundeps    :
    - numpy
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
