name       : python-pandas
version    : 0.21.0
release    : 2
source     :
    - https://github.com/pandas-dev/pandas/archive/v0.21.0.tar.gz : 9de7b333de3af8f4f1b5c83503ccd475e8bdb26505f6309400bd89a3539223d0
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-setuptools
rundeps    :
    - numpy
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
