name       : python-pandas
version    : 2.0.2
release    : 24
source     :
    - https://files.pythonhosted.org/packages/source/p/pandas/pandas-2.0.2.tar.gz : dd5476b6c3fe410ee95926873f377b856dbc4e81a9c605a0dc05aaccc6a7c6c6
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil   # check
    - python-pytest     # check
    - python-pytz       # check
    #- python-versioneer
rundeps    :
    - python-bottleneck # optional
    - python-dateutil
    - python-numexpr
    - python-pytz
    - python-tzdata
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
