name       : python-pandas
version    : 1.4.3
release    : 19
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.4.3/pandas-1.4.3.tar.gz : 2ff7788468e75917574f080cd4681b27e1a7bf36461fe968b49a87b5a54d007c
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil # check
    - python-pytest   # check
    - python-pytz     # check
rundeps    :
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
