name       : python-pandas
version    : 1.2.5
release    : 13
source     :
    - https://github.com/pandas-dev/pandas/releases/download/v1.2.5/pandas-1.2.5.tar.gz : 14abb8ea73fce8aebbb1fb44bec809163f1c55241bcc1db91c2c780e97265033
homepage   : https://pandas.pydata.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful Python data analysis toolkit
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-dateutil # check
    - python-pytest # check
    - python-pytz # check
rundeps    :
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    requires pytest 5
#    %python3_test pytest3 pandas --skip-slow --skip-network --skip-db -m "not single" -n 4 -r sxX
