name       : python-pandas
version    : 0.24.2
release    : 8
source     :
    - https://github.com/pandas-dev/pandas/archive/v0.24.2.tar.gz : 286787f06ac1b7bd322d04f9cf20e14ec3e0bd6b0ec9951456d8c53375545aa1
license    : BSD-3-Clause
component  : programming.python
summary    : Flexible and powerful data analysis / manipulation library for Python,
    providing labeled data structures similar to R data.frame objects, statistical
    functions, and much more.
description: |
    Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more.
builddeps  :
    - cython
    - numpy
    - python-setuptools
rundeps    :
    - python-bottleneck
    - python-dateutil
    - python-numexpr
    - python-pytz
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
